package org.firstinspires.ftc.teamcode.IntoTheDeep.StateRoullete.enums;

public enum PTOStepsToTake {
    EXTENDLIFTFIRSTRANG,
    WHEELIE,
    CLAMPDOWNONBARFIRST,
    EXTENDLIFTTOSECONDBAR,
    EXTENDOBALANCEANDCLOSEWHEELIE,
    CLAMPDOWNONBARSECONDANDRETRACTEXTENDO,
    STANDSTILL,

}
