package org.firstinspires.ftc.teamcode.IntoTheDeep.WraperClasses.TaskRelated;

public enum TaskEnums {
    //outtake
    SPECIMEN_WALL_POSITION,
    CLOSE_CLAW,
    SPECIMEN_CLOSE_CLAW,
    SPECIMEN_BAR_POSITION,//grabs and go

    SAMPLE_STORAGE_POSITION,
    SAMPLE_OVER_BASKET_POSITION,
    SAMPLE_OVER_BASKET_LET_GO,


    //lift

    GIVE_POWER_TILL_POS,
    GIVE_LIFT_POS,


    SPECIMEN_WALL_HEIGHT,
    SPECIMEN_BAR_HEIGHT,


    SAMPLE_STORAGE_HEIGHT,
    SAMPLE_HIGH_BASKET_HEIGHT,
    SAMPLE_LOW_BASKET_HEIGHT,


    //hang logic
    ENGAGEPTO,
    DISENGAGEPTO,
    WHEELIE,
    OVER_BAR_HEIGHT,
    PULL_DOWN,

    //extendo
    EXTEND_TO_POS,
    AFTER_SAMPLE_NEUTRE_POSITION_EXTENDO,
    RETRACT_EXTENDO_FOR_CYCLE,

    //intake
    DROPDOWN_UP,
    DROPDOWN_DOWN,

    NEUTRE_POSITION_GENERAL,


}
