package org.firstinspires.ftc.teamcode.IntoTheDeep.WraperClasses.TaskRelated;

public enum TaskEnumsOverall {

    NEUTRE_POSITION,

    //for sample switch

    SAMPLE_MODE,
    SPECIMEN_MODE,
    WAIT_TO_DRAG_DOWN_LIFT,

    //specimen
    WALL_POSITION,
    CLOSE_CLAW_ON_SPECIMEN,
    DRAG_LIFT_DOWN_SAFELY_AFTER_PUT_SPECIMEN,

    //sample
    GET_EXTENDO_BACK,
    DRAG_LIFT_DOWN,
    BASKET_POS,
    SWITCH_BASKET_OUTTAKE_POS,
    OVER_BASKET_OUTTAKE,
    READY_FOR_TRANSFER_SAMPLE,
    LET_GO_SAMPLE,
    NEUTRE_POSITION_OUTTAKE,
    SAFELY_DRAG_LIFT_DOWN,

    //hang logic

    WHEELIE_LIFT_TO_FIRST_BAR,
    ENGAGE_AND_DRAGDOWN_TILL_POS_ZERO_1,
    DISENGAGE_AND_SET_LIFT_TO_POS_OVER_SECOND_BAR_WHEELIE_RETRACT,
    ENGAGE_AND_DRAGDOWN_TILL_POS_ZERO_2,
}
